### ISSUE TITLE
AMI events get missed

### ISSUE THREAD

**Issue by steinwej** [InterLinked1/cami#6]
It is possible that events from the AMI get missed. This is the case when more than one event are written to the ami_event_pipe before it gets emptied in ami_event_dispatch thread. When the read takes place, there are more than one event  separated by '\0'.  But ami_parse_event counts only 
[before_after.txt](https://github.com/InterLinked1/cami/files/11472529/before_after.txt)
till the first '\0'.

[events_missed_diff.txt](https://github.com/InterLinked1/cami/files/11472521/events_missed_diff.txt)

**Comment by InterLinked1** [comment]
Thanks for the report. I've uploaded a fix here if you want to try that out: https://github.com/InterLinked1/cami/tree/issue-6
Let me know if that resolves your issue.
